#!/bin/bash
# chkconfig: 2345 80 20
# Description: Tomcat Server basic start/shutdown script
# /etc/init.d/tomcat6 -- startup script for the Tomcat 6 servlet engine

export JAVA_HOME=/opt/jdk1.7.0_79
export PATH=$JAVA_HOME/bin:$PATH
TOMCAT_HOME=/tomcat/bin
START_TOMCAT=/tomcat/bin/startup.sh
STOP_TOMCAT=/tomcat/bin/shutdown.sh
TOMCAT_USER=tomcat
start() {
 echo -n "Starting tomcat6: "
 cd $TOMCAT_HOME
 /bin/su - tomcat -c ${START_TOMCAT}
 echo "done."
}

stop() {
 echo -n "Shutting down tomcat6: "
 cd $TOMCAT_HOME
 ${STOP_TOMCAT}
 echo "done."
}

case "$1" in
 
start)
 start
 ;;

stop)
 stop
 ;;

restart)
 stop
 sleep 10
 start
 ;;

*)
 echo "Usage: $0 {start|stop|restart}"

esac
exit 0

